### PR TITLE
Made login page responsive

### PR DESCRIPTION
**Pull request by akadeepesh**
## Description

Fixes: #12 

I have added css to  client/src/pages/Login to make the page responsive

## Type of change

_What type of changes does your code introduce to the wharf? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [x ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

### CODE REVIEW

**Comment by yp969803** [comment]
@akadeepesh can you run `make format` and then commit the changes

**Comment by yp969803** [comment]
Thanks @akadeepesh for the pr, can you squash the commits into one commit in the format
```
rfac: made login page responsive
```

**Comment by akadeepesh** [comment]
@yp969803 Done, please review

**Comment by yp969803** [comment]
@akadeepesh firstly you have also squashed the commit that you havnt made which is `Update MAINTAINER.md`

**Comment by yp969803** [comment]
@akadeepesh the issue is completed

**Pull request closed without merging**
