### PR TITLE
Responsive login page

### PR DESCRIPTION
**Pull request by sowunmi-mayowa**
responsive login UI up and running on all screens

### CODE REVIEW

**Comment by yp969803** [comment]
@sowunmi-mayowa can you run `make format` and then squash all the commits into one

**Comment by sowunmi-mayowa** [comment]
Looking into how i can run make command already
i'll push the updates soon

**Comment by yp969803** [comment]
@sowunmi-mayowa if you are using windows, you should use wsl

**Comment by sowunmi-mayowa** [comment]
Alright thank you 
I have wsl installed already, I’ll work on it

**Comment by sowunmi-mayowa** [comment]
{75BC4EBA-573D-4B81-834C-FA9894FAAC4D}
this is the error i've been etting

**Comment by yp969803** [comment]
@sowunmi-mayowa you can run `npm run format` at the directory which contains package.json

**Comment by yp969803** [comment]
@sowunmi-mayowa thanks, if you like the project, please give it a star.

**Comment by sowunmi-mayowa** [comment]
you're welcome @yp969803

**Pull request merged**
