### PR TITLE
made component details page responsive

### PR DESCRIPTION
**Pull request by anveshthakur**
## Description

Fixes: #24 

- fixes in the responsiveness in of component details page 
- added media queries for font sizes for different font sizes
- added word break property for text overflow

## Type of change

_What type of changes does your code introduce to the wharf? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [x] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Verification

Please check the [testing guidelines](../docs/TESTING.md) for recommendations about automated tests.
have tested it on different screen sizes

### CODE REVIEW

**Comment by anveshthakur** [comment]
hi @yp969803, let me know if anything else is required

**Comment by yp969803** [comment]
@anveshthakur can you run `make format`

**Comment by anveshthakur** [comment]
done.

**Comment by yp969803** [comment]
Thanks

**Pull request merged**
